# Generated by Django 2.2.3 on 2019-07-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_heroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
